-- Reference corpus and archived personal-edition records.

        

        CREATE TABLE IF NOT EXISTS schema_version (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id = 1),
            version TEXT NOT NULL,
            built_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS sources (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            path TEXT NOT NULL UNIQUE,
            file_name TEXT NOT NULL,
            sha256 TEXT NOT NULL,
            encoding TEXT NOT NULL,
            source_type TEXT NOT NULL,
            status TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS books (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id INTEGER NOT NULL REFERENCES sources(id),
            name TEXT NOT NULL,
            UNIQUE(source_id, name)
        );

        CREATE TABLE IF NOT EXISTS passages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id INTEGER NOT NULL REFERENCES sources(id),
            book_id INTEGER NOT NULL REFERENCES books(id),
            section_title TEXT NOT NULL,
            ordinal INTEGER NOT NULL,
            text TEXT NOT NULL,
            source_line_start INTEGER NOT NULL,
            source_line_end INTEGER NOT NULL,
            status TEXT NOT NULL,
            can_generate INTEGER NOT NULL DEFAULT 0 CHECK (can_generate IN (0, 1)),
            reviewed_at TEXT,
            reviewer TEXT,
            review_note TEXT
        );

        CREATE TABLE IF NOT EXISTS eras (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id INTEGER NOT NULL REFERENCES sources(id),
            region TEXT NOT NULL,
            category TEXT NOT NULL,
            era_name TEXT NOT NULL,
            period TEXT NOT NULL,
            duration TEXT NOT NULL,
            status TEXT NOT NULL,
            source_line INTEGER NOT NULL DEFAULT 0,
            record_type TEXT NOT NULL DEFAULT '正式年号',
            person TEXT NOT NULL DEFAULT '',
            note TEXT NOT NULL DEFAULT ''
        );

        CREATE TABLE IF NOT EXISTS directions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE
        );

        CREATE TABLE IF NOT EXISTS direction_keywords (
            direction_id INTEGER NOT NULL REFERENCES directions(id),
            keyword TEXT NOT NULL,
            PRIMARY KEY(direction_id, keyword)
        );

        CREATE TABLE IF NOT EXISTS audit_issues (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_id INTEGER REFERENCES sources(id),
            issue_type TEXT NOT NULL,
            detail TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT '待处理',
            reviewed_at TEXT,
            reviewer TEXT,
            review_note TEXT
        );

        CREATE TABLE IF NOT EXISTS name_runs (
            id TEXT PRIMARY KEY,
            request_json TEXT NOT NULL,
            bazi_json TEXT,
            random_seed INTEGER,
            rule_version TEXT NOT NULL,
            status TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS candidates (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id TEXT NOT NULL REFERENCES name_runs(id),
            full_name TEXT NOT NULL,
            given_name TEXT NOT NULL,
            book TEXT,
            section_title TEXT,
            source_passage_id INTEGER REFERENCES passages(id),
            source_text TEXT,
            source_offset INTEGER NOT NULL DEFAULT 0,
            direction TEXT,
            wuxing_json TEXT,
            pinyin TEXT,
            pinyin_tone TEXT,
            origin_type TEXT NOT NULL,
            base_score INTEGER NOT NULL,
            UNIQUE(run_id, full_name)
        );

        CREATE TABLE IF NOT EXISTS candidate_phrases (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            passage_id INTEGER NOT NULL REFERENCES passages(id),
            phrase TEXT NOT NULL,
            source_offset INTEGER NOT NULL,
            direction TEXT NOT NULL,
            origin_type TEXT NOT NULL,
            quality_score INTEGER NOT NULL,
            status TEXT NOT NULL,
            note TEXT,
            UNIQUE(passage_id, phrase, direction)
        );

        CREATE TABLE IF NOT EXISTS characters (
            char TEXT PRIMARY KEY,
            pinyin TEXT NOT NULL,
            pinyin_tone TEXT NOT NULL,
            source TEXT NOT NULL,
            status TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS character_elements (
            char TEXT NOT NULL REFERENCES characters(char),
            element TEXT NOT NULL,
            method TEXT NOT NULL,
            confidence TEXT NOT NULL,
            status TEXT NOT NULL,
            note TEXT,
            reviewed_at TEXT,
            reviewer TEXT,
            PRIMARY KEY(char, method)
        );

        CREATE TABLE IF NOT EXISTS model_candidates (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id TEXT NOT NULL REFERENCES name_runs(id),
            name TEXT NOT NULL,
            passage_id INTEGER REFERENCES passages(id),
            origin_type TEXT NOT NULL,
            meaning TEXT NOT NULL,
            style_json TEXT NOT NULL,
            risks_json TEXT NOT NULL,
            source_offset INTEGER NOT NULL DEFAULT -1,
            provider TEXT NOT NULL,
            model TEXT NOT NULL,
            status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE(run_id, name)
        );

        CREATE TABLE IF NOT EXISTS model_metrics (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id TEXT NOT NULL REFERENCES name_runs(id),
            provider TEXT NOT NULL,
            model TEXT NOT NULL,
            latency_ms INTEGER NOT NULL,
            input_tokens INTEGER,
            output_tokens INTEGER,
            estimated_cost DOUBLE PRECISION,
            status TEXT NOT NULL,
            error TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS favorites (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            collection_id TEXT NOT NULL,
            run_id TEXT,
            full_name TEXT NOT NULL,
            given_name TEXT NOT NULL,
            pinyin TEXT,
            pinyin_tone TEXT,
            book TEXT,
            section_title TEXT,
            source_passage_id INTEGER,
            source_text TEXT,
            source_offset INTEGER,
            direction TEXT,
            wuxing_json TEXT,
            origin_type TEXT,
            base_score INTEGER,
            note TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            UNIQUE(collection_id, full_name)
        );

        CREATE TABLE IF NOT EXISTS feedback (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            collection_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            full_name TEXT NOT NULL,
            feedback_type TEXT NOT NULL,
            score INTEGER,
            comment TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            UNIQUE(collection_id, run_id, full_name)
        );

        CREATE INDEX IF NOT EXISTS idx_passages_book ON passages(book_id);
        CREATE INDEX IF NOT EXISTS idx_passages_section ON passages(section_title);
        CREATE INDEX IF NOT EXISTS idx_passages_text ON passages(text);
        CREATE INDEX IF NOT EXISTS idx_eras_region ON eras(region);
        