CREATE TABLE IF NOT EXISTS app_users (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS app_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname TEXT NOT NULL CHECK (char_length(surname) BETWEEN 1 AND 2),
    name_length INTEGER NOT NULL CHECK (name_length IN (1, 2)),
    enabled BOOLEAN NOT NULL DEFAULT true,
    last_scheduled TIMESTAMPTZ NOT NULL DEFAULT 'epoch',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(surname, name_length)
);
CREATE TABLE IF NOT EXISTS app_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES app_profiles(id),
    given_name TEXT NOT NULL,
    full_name TEXT NOT NULL,
    book TEXT NOT NULL,
    passage_id BIGINT NOT NULL REFERENCES passages(id),
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(profile_id, given_name)
);
CREATE INDEX IF NOT EXISTS app_materials_profile ON app_materials(profile_id, id);
CREATE TABLE IF NOT EXISTS app_deliveries (
    owner TEXT NOT NULL REFERENCES app_users(id),
    full_name TEXT NOT NULL,
    material_id BIGINT NOT NULL REFERENCES app_materials(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(owner, full_name),
    UNIQUE(owner, material_id)
);
CREATE TABLE IF NOT EXISTS app_receipts (
    owner TEXT NOT NULL REFERENCES app_users(id),
    request_id UUID NOT NULL,
    fingerprint TEXT NOT NULL,
    response JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(owner, request_id)
);
CREATE TABLE IF NOT EXISTS app_favorites (
    owner TEXT NOT NULL,
    material_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(owner, material_id),
    FOREIGN KEY(owner, material_id) REFERENCES app_deliveries(owner, material_id)
);
CREATE TABLE IF NOT EXISTS app_feedback (
    owner TEXT NOT NULL,
    material_id BIGINT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('不喜欢', '出处问题', '释义问题')),
    comment TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(owner, material_id),
    FOREIGN KEY(owner, material_id) REFERENCES app_deliveries(owner, material_id)
);
CREATE TABLE IF NOT EXISTS app_nonces (
    nonce TEXT PRIMARY KEY,
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS app_nonces_expiry ON app_nonces(expires_at);
CREATE TABLE IF NOT EXISTS app_rate_limits (
    owner TEXT PRIMARY KEY REFERENCES app_users(id),
    minute_window BIGINT NOT NULL,
    requests INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS app_source_progress (
    profile_id BIGINT NOT NULL REFERENCES app_profiles(id),
    book TEXT NOT NULL,
    batches INTEGER NOT NULL DEFAULT 0,
    accepted INTEGER NOT NULL DEFAULT 0,
    failures INTEGER NOT NULL DEFAULT 0,
    retry_at TIMESTAMPTZ NOT NULL DEFAULT 'epoch',
    last_started TIMESTAMPTZ NOT NULL DEFAULT 'epoch',
    last_error TEXT NOT NULL DEFAULT '',
    PRIMARY KEY(profile_id, book)
);
CREATE TABLE IF NOT EXISTS app_attempts (
    profile_id BIGINT NOT NULL REFERENCES app_profiles(id),
    book TEXT NOT NULL,
    given_name TEXT NOT NULL,
    PRIMARY KEY(profile_id, book, given_name)
);
CREATE TABLE IF NOT EXISTS app_budget (
    day DATE PRIMARY KEY,
    batches INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS app_worker (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    heartbeat TIMESTAMPTZ NOT NULL DEFAULT now(),
    status TEXT NOT NULL,
    last_error TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS app_migrations (
    id TEXT PRIMARY KEY,
    summary JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
