-- One row per model request reservation. Keep recent rows for rolling windows.
CREATE TABLE IF NOT EXISTS app_model_call_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserved_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX IF NOT EXISTS app_model_call_reservations_time
    ON app_model_call_reservations(reserved_at);
