server {
    listen 80;
    listen [::]:80;
    server_name name.sensen.li;
    # HTTP 强转 HTTPS
    rewrite ^(.*)$ https://${server_name}$1 permanent;
}

server {
    # 监听 8043，接收来自 Nginx stream 模块（443端口 ssl_preread）转发的流量
    listen 8043 ssl http2;
    listen [::]:8043 ssl http2;
    server_name name.sensen.li;

    # SSL 证书配置（使用 acme.sh 容器自动更新的 *.sensen.li 通配符证书）
    ssl_certificate /etc/certs/sensen.li_ecc/fullchain.cer;
    ssl_certificate_key /etc/certs/sensen.li_ecc/sensen.li.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    error_page 497 https://$host$request_uri;

    # 监控指标禁止外部访问
    location = /metrics {
        return 403 "监控指标仅供内部访问\n";
    }

    location / {
        client_max_body_size 64m;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        proxy_buffering off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        # 反向代理到本机 Docker 容器服务端口
        proxy_pass http://127.0.0.1:8000;
    }
}
